name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    types: [closed]
    branches: [ releases ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Save Version
      run: |
        echo "REPO_NAME=iboxindia" >> $GITHUB_ENV
        echo "REPO_URL=https://github.com/${{ github.repository }}" >> $GITHUB_ENV
        echo "REPOSITORY_OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV

        version=`sed -n 's/^ \* Version: \(.*\)$/\1/p' ${{ env.REPO_NAME }}.php`
        echo "VERSION=$version" >> $GITHUB_ENV
        name=`sed -n 's/^ \* Plugin Name: \(.*\)$/\1/p' ${{ env.REPO_NAME }}.php`
        echo "ASSET_NAME=$name" >> $GITHUB_ENV
        author=`sed -n 's/^ \* Author: \(.*\)$/\1/p' ${{ env.REPO_NAME }}.php`
        echo "AUTHOR=$author" >> $GITHUB_ENV
        
    - name: Create zip archive
      run: |
        /usr/bin/git archive -v -o ${{ env.REPO_NAME }}.zip --worktree-attributes HEAD
        /usr/bin/unzip ${{ env.REPO_NAME }}.zip -d ${{ env.REPO_NAME }}
        /bin/rm -rf ${{ env.REPO_NAME }}.zip
        /bin/rm -rf .github
        /usr/bin/zip -r ${{ env.REPO_NAME }}.zip ${{ env.REPO_NAME }}
        echo $VERSION
    - name: Upload screenshot to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: screenshot.png
        asset_name: screenshot.png
        tag: ${{ env.VERSION }}
        overwrite: true
        body: "${{ env.ASSET_NAME }} ${{ env.VERSION }}"
        
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.REPO_NAME }}.zip
        asset_name: ${{ env.REPO_NAME }}-${{ env.VERSION }}.zip
        tag: ${{ env.VERSION }}
        overwrite: true
        body: "${{ env.ASSET_NAME }} ${{ env.VERSION }}"
    - name: Update the version in database
      run: |
        curl  --header "Content-Type: application/json" \
              --request POST \
              --data '{"type": "plugin","author": "${{ env.AUTHOR }}","name": "${{ env.ASSET_NAME }}","version": "${{ env.VERSION }}","wp_minimum_version": "5.0.0","wp_tested_version": "5.4.2","php_required_version": "7.0.1","repoType": "github","repoUrl": "${{ env.REPO_URL }}","repoOwner": "${{ env.REPOSITORY_OWNER }}"}' \
              https://wordpress.iboxindia.com/updates/${{ env.REPO_NAME }}