name: Deploy to WordPress.org
on:
  push:
    tags:
    - "v*"
  pull_request:
    types: [closed]
    tags:
    - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Create zip archive
        run: |
          /usr/bin/git archive -v -o iboxindia.zip --worktree-attributes HEAD
          /usr/bin/unzip iboxindia.zip -d iboxindia
          /bin/rm -rf iboxindia.zip
          /bin/rm -rf .github
          /usr/bin/zip -r iboxindia.zip iboxindia

      - name: WordPress Plugin Deploy
        uses: nk-o/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.WP_SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.WP_SVN_USERNAME }}
          SLUG: iboxindia